### ISSUE TITLE
Spec Backend

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/redemption#1]
Backend Endpoint;

**1) Create links** POST /v1/links/create

- endpoint should be protected by the password (bearer token)

Request:
```
{
    assets: [
        {
            coin: 714,
            token_id: "BUSD-BD1",
            amount: 25000000
        },
        {
            coin: 714,
            token_id: "BNB",
            amount: 10000000
        }
    ],
    link_count: 50,
    provider: "redeem.herokuapp.com"
}
```

Response:
```
[ 
    { 
          link: "https://links.trustwallet.com?redeem?code=12312321&provider=redeem.herokuapp.com",
          code: "12312321",
          assets: [
        {
            coin: 714,
            token_id: "BUSD-BD1",
            amount: 25000000
        },
        {
            coin: 232,
            token_id: "BNB",
            amount: 10000000
        }
    ],
     }
]
```

**2) POST /v1/referral/redeem**

Request:
```
JSON:

{
    "code": "123".
    "observers":  [] // list of addresses 
}


//Additional data
type Observer struct {
	Coin       int      `json:"coin"`
	PublicKeys []string `json:"publicKeys,omitempty" bson:"publicKeys,omitempty" `
	Addresses  []string `json:"addresses,omitempty" bson:"addresses,omitempty`
}
```

Response:
```
const (
	RedeemResultTypeError   RedeemResultType = "error"
	RedeemResultTypeSuccess RedeemResultType = "success"
)
type RedeemResult struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	ImageURL    string           `json:"image_url,omitempty"`
	Type        RedeemResultType `json:"type"`
}
```

**Comment by onggunhao** [comment]
@vikmeup A few thoughts (cc @hiteck)

1. For **Create Links API** v1 for the purposes of MVP, each link needs to send 25 BUSD and 0.1 BNB (amounts may vary). This is so new users have enough gas to send transactions. This also applies for ERC-20 tokens.

2. How do you envision us (a) creating and (b) persisting the private key of the redemption server's wallet? 

3. **Random thought**: is persisting cleartext redemption codes in database optimal? Should we just store the SHA256 of redemption codes, and only allow the user to download a list of cleartext codes when creating it?

4. [For future note] When we do support multiple chains, we will need to have some API to "create wallet". For ETH-based chains, we can use smart contract functions. For Binance Chain, users will need to send to an address for the wallet created before creating links

**Comment by vikmeup** [comment]
1) This make sense, updated request/response
2) For now pro user needs to create a wallet and enter when deploying (12 words), let's keep it simple 
3) This make sense too. I would keep it simple for now, this could be a security feature in the future.
4) `observers` is just an internal name for list of user's addresses, we can rename this.
