### ISSUE TITLE
GET All Links incorrectly shows assets as null

### ISSUE THREAD

**Issue by onggunhao** [trustwallet/redemption#11]
## Summary of Bug

* GET All Links API returns list of links
* Individual links seem to be missing the `asset > assets` data field, which shows as null
* GET a specific link shows that the correct `asset > assets` data field

## Steps to Reproduce

On the `redeem-trust.herokuapp.com` testing server, look for code `Ev6-t3V-dMK`

![image](https://user-images.githubusercontent.com/518024/70928386-e98ad200-206b-11ea-831a-3bcaa4364052.png)

![image](https://user-images.githubusercontent.com/518024/70928449-0aebbe00-206c-11ea-95c5-bb7f042e68ba.png)

![image](https://user-images.githubusercontent.com/518024/70928510-2b1b7d00-206c-11ea-8011-eac82b6a2d01.png)

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Pantani** [comment]
solved 
https://github.com/trustwallet/redemption/pull/12
